// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4SfGOpf6oISf0fbJSHDoO-UE1tMS1WEM',
    appId: '1:43141891785:web:68ff2d7e305a9899a42f18',
    messagingSenderId: '43141891785',
    projectId: 'hedieaty-app',
    authDomain: 'hedieaty-app.firebaseapp.com',
    storageBucket: 'hedieaty-app.firebasestorage.app',
    measurementId: 'G-X8N11NWDJF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBswtfT1uDoMRp4EHf7q5iZiAqxHQ-p9yw',
    appId: '1:43141891785:android:7e33404eb54178c4a42f18',
    messagingSenderId: '43141891785',
    projectId: 'hedieaty-app',
    storageBucket: 'hedieaty-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI8QvCZTR_hgVKnP6Wh5pHNk5R9t0t5YI',
    appId: '1:43141891785:ios:8a43b124098d33cfa42f18',
    messagingSenderId: '43141891785',
    projectId: 'hedieaty-app',
    storageBucket: 'hedieaty-app.firebasestorage.app',
    iosBundleId: 'com.example.hedieaty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBI8QvCZTR_hgVKnP6Wh5pHNk5R9t0t5YI',
    appId: '1:43141891785:ios:8a43b124098d33cfa42f18',
    messagingSenderId: '43141891785',
    projectId: 'hedieaty-app',
    storageBucket: 'hedieaty-app.firebasestorage.app',
    iosBundleId: 'com.example.hedieaty',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4SfGOpf6oISf0fbJSHDoO-UE1tMS1WEM',
    appId: '1:43141891785:web:114069f5fddd7f12a42f18',
    messagingSenderId: '43141891785',
    projectId: 'hedieaty-app',
    authDomain: 'hedieaty-app.firebaseapp.com',
    storageBucket: 'hedieaty-app.firebasestorage.app',
    measurementId: 'G-NY58XCL9FT',
  );
}
